Add controllers
HaMeCTHuK/java-shareit pull request #1
Opened 2024-02-24 09:01 UTC by HaMeCTHuK

All test postman test OK.

2024-02-25 08:32 UTC, LexLippi requested changes
Привет!

Неплохая работа!

Есть некоторое количество замечаний, которые необходимо исправить!

Желаю удачи!

2024-02-25 08:32 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +public class BookingServiceImpl implements BookingService {
Нам точно нужны пустой интерфейс и его пустая реализация?

2024-02-25 08:32 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    private final UserService userService;
Почему `Autowired` только у одного из сервисов?

2024-02-25 08:32 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        return itemService.searchItemsByText(text, userId);
Можно использовать тернарный оператор

2024-02-25 08:32 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    }*/
Лучше удалять такое, а не комментировать, система контроля версий позволяет восстановить такие участки кода

2024-02-25 08:32 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +    private Long generatedId = 0L;
Генератор идентификаторов лучше перенести внутрь репозитория

2024-02-25 08:32 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/request/ItemRequestService.java
> +public interface ItemRequestService {
Аналогичный вопрос про пустой интерфейс и реализацию

2024-02-25 08:32 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    private Long generatedId = 0L;
Аналогичное замечание

2024-02-25 20:18 UTC, HaMeCTHuK commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +public class BookingServiceImpl implements BookingService {
Интерфейс пока пустой, т.к. был изначально в шаблоне, будет использоваться в дальнейших спринтах

2024-02-25 20:18 UTC, HaMeCTHuK commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    private final UserService userService;
Исправил)

2024-02-25 20:18 UTC, HaMeCTHuK commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    }*/
Понял, удаляю.

2024-02-25 20:18 UTC, HaMeCTHuK commented on src/main/java/ru/practicum/shareit/request/ItemRequestService.java
> +public interface ItemRequestService {
Интерфейс пока пустой, т.к. был изначально в шаблоне, будет использоваться в дальнейших спринтах

2024-02-25 20:18 UTC, HaMeCTHuK commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    private Long generatedId = 0L;
Переделал)

2024-02-25 20:19 UTC, HaMeCTHuK commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +    private Long generatedId = 0L;
Понял, реализацию переделал

2024-02-25 20:19 UTC, HaMeCTHuK commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        return itemService.searchItemsByText(text, userId);
Выполнено)

2024-02-26 07:41 UTC, LexLippi commented
Привет!

Отличная работа!

Желаю удачи в следующих спринтах!

2024-03-30 14:53 UTC, merged