Add item requests
HaMeCTHuK/java-shareit pull request #4
Opened 2024-04-08 20:42 UTC by HaMeCTHuK

2024-05-18 10:53 UTC, LexLippi requested changes
Привет!

Отличная работа!

Есть некоторое количество замечаний, которые необходимо исправить!

Желаю удачи!

2024-05-18 10:53 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                                             @RequestParam(required = false, defaultValue = "ALL") String state,
Нет необходимости в `required = false`, когда используем `defaultValue`, оно по умолчанию устанавливается таковым

2024-05-18 10:53 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                                             @RequestParam(name = "from", defaultValue = "0") Integer from,
Нет необходимости в `name`, если оно совпадает с именем переменной

2024-05-18 10:53 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                                               @RequestParam(name = "size", defaultValue = "10") Integer size) {
Замечания аналогичные тем, что выше написал

2024-05-18 10:53 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/common/FromSizeRequest.java
> +        if (from < 0) {
А `size` должен быть строго положительным иначе в нем нет смысла

2024-05-18 10:53 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepository.java
> +    @Query("select ie from ItemEntity ie where ie.request.id in (:itemRequestsId)")
Лучше использовать просто:

```sql
ie.request.id = :itemRequestsId
```

2024-05-18 10:53 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/request/ItemRequestController.java
> +    public ItemRequestDto createRequest(@RequestHeader("X-Sharer-User-Id") Long userId, @Valid @RequestBody ItemRequestDto itemRequestDto) {
строку `X-Sharer-User-Id` стоит вынести в константу проекта

2024-05-18 10:53 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/request/ItemRequestController.java
> +            @RequestParam(name = "size", defaultValue = "10") Integer size) {
Про `name` уже писал

2024-05-19 10:15 UTC, HaMeCTHuK commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                                             @RequestParam(required = false, defaultValue = "ALL") String state,
Понял, спасибо! Исправил

2024-05-19 10:17 UTC, HaMeCTHuK commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                                               @RequestParam(name = "size", defaultValue = "10") Integer size) {
Исправил

2024-05-19 10:18 UTC, HaMeCTHuK commented on src/main/java/ru/practicum/shareit/common/FromSizeRequest.java
> +        if (from < 0) {
Ошибка!,Добавил еще условие проверки

2024-05-19 10:18 UTC, HaMeCTHuK commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepository.java
> +    @Query("select ie from ItemEntity ie where ie.request.id in (:itemRequestsId)")
Исправил

2024-05-19 10:18 UTC, HaMeCTHuK commented on src/main/java/ru/practicum/shareit/request/ItemRequestController.java
> +    public ItemRequestDto createRequest(@RequestHeader("X-Sharer-User-Id") Long userId, @Valid @RequestBody ItemRequestDto itemRequestDto) {
Сделал отдельную константу, исправил во всех контроллерах

2024-05-19 10:19 UTC, HaMeCTHuK commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                                             @RequestParam(name = "from", defaultValue = "0") Integer from,
Спасибо, исправил

2024-05-19 10:19 UTC, HaMeCTHuK commented on src/main/java/ru/practicum/shareit/request/ItemRequestController.java
> +            @RequestParam(name = "size", defaultValue = "10") Integer size) {
Исправил.

2024-05-19 20:36 UTC, LexLippi commented
Привет!

Отличная работа!

Желаю удачи в следующих спринтах!

2024-06-01 16:27 UTC, merged