Add docker
HaMeCTHuK/java-shareit pull request #5
Opened 2024-06-07 09:36 UTC by HaMeCTHuK

first pull

2024-06-09 17:49 UTC, LexLippi requested changes
Привет!

Отличная работа!

Есть пара мелких замечаний, которые необходимо исправить!

Желаю удачи!

2024-06-09 17:49 UTC, LexLippi commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                                              @Positive @RequestParam(name = "size", defaultValue = "10") Integer size) {
Нет смысла в поле `name`, если оно совпадает с названием локальной переменной

2024-06-09 17:49 UTC, LexLippi commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    public ResponseEntity<Object> approve(@PathVariable Long bookingId, @RequestHeader("X-Sharer-User-Id") Long userId,
Строку `"X-Sharer-User-Id"` стоит вынести в константу проекта

2024-06-11 07:51 UTC, KirPyt reviewed
Приветствую!

Самое важное в данной работе - это внимательно разделить код между микросервисами `gateway` и `server`, убрать валидацию из сервера (валидация в ДТО-шках, контроллерах, pom файле). Так же разрешается убрать только те тесты, которые могут перестать проходить из-за отсутствия валидации на стороне сервера, остальные тесты надо оставить.

Некоторые замечания и советы актуальны и для остальных частей кода, поэтому стоит обратить внимание и на другие аналогичные места в коде, чтобы всё поправить

Если возникнут вопросы по ревью, то пишите мне в Пачку, обсудим

2024-06-11 07:51 UTC, KirPyt commented on gateway/src/main/java/ru/practicum/shareit/exceptions/exceptionHandler/ErrorHandler.java
> +}
Надо ещё добавить хендлер для отлавливания 500-ой ошибки. Надо будет ловить ошибки класса `Throwable`. Ошибка 500 определяет ошибки, вызванные разными причинами на сервере (это проверяемые и непроверяемые исключения), а ошибки `RuntimeException`, которые Вы ловите в данный момент, являются только проверяемыми.
Более подробно Вы можете почитать здесь:
https://www.baeldung.com/java-exceptions
(Раздел Exception Hierarchy)

2024-06-11 07:51 UTC, KirPyt commented on gateway/src/main/java/ru/practicum/shareit/exceptions/exceptionHandler/ErrorHandler.java
> +        return new ErrorResponse(String.format("Ошибка: %s", e.getParameter()));
Рекомендую добавить логирование стек трейса в каждый хендлер

2024-06-11 07:51 UTC, KirPyt commented on gateway/src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public ResponseEntity<Object> findById(@PathVariable Long id, @RequestHeader("X-Sharer-User-Id") Long ownerId) {
`"X-Sharer-User-Id"` рекомендую вынести в константу по аналогии с остальными контроллерами
Аналогично и для остальных подобных мест

2024-06-11 07:51 UTC, KirPyt commented on gateway/src/main/java/ru/practicum/shareit/item/ItemController.java
> +                                  @RequestParam(defaultValue = "0") int from,
Здесь так же стоит сделать валидацию через аннотации, по аналогии с контроллером бронирований
Аналогично и для остальных подобных мест

2024-06-11 07:51 UTC, KirPyt commented on gateway/src/main/java/ru/practicum/shareit/itemRequest/ItemRequestController.java
> +@RestController
Так как Вы далее используете `ResponseEntity`, то здесь и в подобных местах можно использовать просто `@Controller`

2024-06-11 07:51 UTC, KirPyt commented on gateway/src/main/java/ru/practicum/shareit/itemRequest/dto/ItemRequestRequestDto.java
> +    String description;
Надо добавить модификатор доступа

2024-06-11 07:51 UTC, KirPyt commented on server/pom.xml
> +			<artifactId>spring-boot-starter-validation</artifactId>
Валидацию из сервера убираем

2024-06-11 07:51 UTC, KirPyt commented on server/pom.xml
> +			<artifactId>hibernate-validator</artifactId>
Так же из сервера убираем

2024-06-11 07:51 UTC, KirPyt commented on src/test/java/ru/practicum/shareit/item/entity/CommentEntityTest.java
> -public class CommentEntityTest {
Почему данный тест было решено удалить?

2024-06-11 07:51 UTC, KirPyt commented on server/src/test/java/ru/practicum/shareit/item/repository/ItemRepositoryTest.java
> -    public void testSearch() {
Почему данный тест было решено удалить?

2024-06-11 10:33 UTC, HaMeCTHuK commented on gateway/src/main/java/ru/practicum/shareit/exceptions/exceptionHandler/ErrorHandler.java
> +}
Понял. Поправил. Спасибо

2024-06-11 10:33 UTC, HaMeCTHuK commented on gateway/src/main/java/ru/practicum/shareit/exceptions/exceptionHandler/ErrorHandler.java
> +        return new ErrorResponse(String.format("Ошибка: %s", e.getParameter()));
Логирование добавил

2024-06-11 10:33 UTC, HaMeCTHuK commented on gateway/src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public ResponseEntity<Object> findById(@PathVariable Long id, @RequestHeader("X-Sharer-User-Id") Long ownerId) {
Как то я проглядел этот момент. Исправил везьде

2024-06-11 10:34 UTC, HaMeCTHuK commented on gateway/src/main/java/ru/practicum/shareit/item/ItemController.java
> +                                  @RequestParam(defaultValue = "0") int from,
Добавил аннотации валидации

2024-06-11 10:34 UTC, HaMeCTHuK commented on gateway/src/main/java/ru/practicum/shareit/itemRequest/ItemRequestController.java
> +@RestController
Исправил

2024-06-11 10:35 UTC, HaMeCTHuK commented on server/pom.xml
> +			<artifactId>spring-boot-starter-validation</artifactId>
Я плаваю еще в помниках... Надо это дело подтянуть. Спасибо, убрал

2024-06-11 10:36 UTC, HaMeCTHuK commented on src/test/java/ru/practicum/shareit/item/entity/CommentEntityTest.java
> -public class CommentEntityTest {
Тесты вырезал когда у меня все сломалось. Сейчас данные тасты добавил, переделал. Единственное один тест в ItemController убрал, т.к. убрал аннотации валидации из сервера

2024-06-11 10:36 UTC, HaMeCTHuK commented on server/src/test/java/ru/practicum/shareit/item/repository/ItemRepositoryTest.java
> -    public void testSearch() {
вернул

2024-06-11 11:03 UTC, HaMeCTHuK commented on gateway/src/main/java/ru/practicum/shareit/itemRequest/dto/ItemRequestRequestDto.java
> +    String description;
Добавил

2024-06-11 11:04 UTC, HaMeCTHuK commented on server/pom.xml
> +			<artifactId>hibernate-validator</artifactId>
Убрал, спасибо

2024-06-12 09:00 UTC, KirPyt reviewed
Здравствуйте!

Посмотрел Ваш ПР, заметил, что ещё остались аннотации валидации в `UserController` и `ItemRequestController`, стоит внимательно проверить код, чтобы разделение было полным. В остальном замечаний нет, Ваш проект зачтён

Хорошего дня!

2024-06-28 09:15 UTC, merged